name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant Gradle execution right
        run: chmod +x ./gradlew
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'

      - name: Grant Gralde execution right
        run: git update-index --chmod=+x ./gradlew
        if: matrix.os == 'windows-latest'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Gradle Test
        run: ./gradlew test